/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : dspiCom1.h
**     Project     : TestKSDKProjectSerial
**     Processor   : MK64FN1M0VLL12
**     Component   : fsl_dspi
**     Version     : Component 1.2.0, Driver 01.00, CPU db: 3.00.000
**     Repository  : KSDK 1.2.0
**     Compiler    : GNU C Compiler
**     Date/Time   : 2015-08-31, 18:10, # CodeGen: 13
**     Contents    :
**         DSPI_DRV_IRQHandler              - void DSPI_DRV_IRQHandler(uint32_t instance);
**         DSPI_DRV_MasterInit              - dspi_status_t DSPI_DRV_MasterInit(uint32_t instance,dspi_master_state_t *...
**         DSPI_DRV_MasterDeinit            - dspi_status_t DSPI_DRV_MasterDeinit(uint32_t instance);
**         DSPI_DRV_MasterSetDelay          - dspi_status_t DSPI_DRV_MasterSetDelay(uint32_t instance,dspi_delay_type_t...
**         DSPI_DRV_MasterConfigureBus      - dspi_status_t DSPI_DRV_MasterConfigureBus(uint32_t instance,const...
**         DSPI_DRV_MasterTransferBlocking  - dspi_status_t DSPI_DRV_MasterTransferBlocking(uint32_t instance,const...
**         DSPI_DRV_MasterTransfer          - dspi_status_t DSPI_DRV_MasterTransfer(uint32_t instance,const dspi_device_t *...
**         DSPI_DRV_MasterGetTransferStatus - dspi_status_t DSPI_DRV_MasterGetTransferStatus(uint32_t instance,uint32_t *...
**         DSPI_DRV_MasterAbortTransfer     - dspi_status_t DSPI_DRV_MasterAbortTransfer(uint32_t instance);
**         DSPI_DRV_MasterIRQHandler        - void DSPI_DRV_MasterIRQHandler(uint32_t instance);
**         DSPI_DRV_SlaveInit               - dspi_status_t DSPI_DRV_SlaveInit(uint32_t instance,dspi_slave_state_t *...
**         DSPI_DRV_SlaveDeinit             - dspi_status_t DSPI_DRV_SlaveDeinit(uint32_t instance);
**         DSPI_DRV_SlaveTransferBlocking   - dspi_status_t DSPI_DRV_SlaveTransferBlocking(uint32_t instance,const uint8_t...
**         DSPI_DRV_SlaveTransfer           - dspi_status_t DSPI_DRV_SlaveTransfer(uint32_t instance,const uint8_t *...
**         DSPI_DRV_SlaveAbortTransfer      - dspi_status_t DSPI_DRV_SlaveAbortTransfer(uint32_t instance);
**         DSPI_DRV_SlaveGetTransferStatus  - dspi_status_t DSPI_DRV_SlaveGetTransferStatus(uint32_t instance,uint32_t *...
**         DSPI_DRV_SlaveIRQHandler         - void DSPI_DRV_SlaveIRQHandler(uint32_t instance);
**
**     Copyright : 1997 - 2015 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file dspiCom1.h
** @version 01.00
*/         
/*!
**  @addtogroup dspiCom1_module dspiCom1 module documentation
**  @{
*/         
#ifndef __dspiCom1_H
#define __dspiCom1_H
/* MODULE dspiCom1. */

/* Include inherited beans */
#include "clockMan1.h"
#include "osa1.h"
#include "Cpu.h"

/*! @brief Device instance number */
#define FSL_DSPICOM1 1
/*! @brief dspiCom1 component mode */
#define DSPICOM1_DMA_MODE 0U

/*! @brief Driver state structure. Generated due to enabled auto initialization */
extern dspi_master_state_t dspiCom1_MasterState;

/*! @brief Driver calculated baudrate is returned from DSPI_DRV_MasterInit() call.
    Generated due to enabled auto initialization */
extern uint32_t dspiCom1_calculatedBaudRate;
  
/*! @brief Master bus configuration declaration */
extern const dspi_device_t dspiCom1_BusConfig0;
    
/*! @brief Master configuration declaration */
extern const dspi_master_user_config_t dspiCom1_MasterConfig0;
    

#endif
/* ifndef __dspiCom1_H */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
